import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createAppService, type AppService } from '../src/core/service.js';
import { validatePlan } from '../src/core/validation.js';
import { Store, id, now } from '../src/core/store.js';
import type { Runner, RunnerRequest, RunnerCallbacks } from '../src/runtime/contracts.js';
import type { Executor } from '../src/execution/contracts.js';
import type { Project, TaskSnapshot, ImpactPreview } from '../src/shared/contracts.js';
const draft={sequence:1,summary:'Update the sample and verify it',observations:[{kind:'fact' as const,text:'Sample repository'}],nodes:[{id:'edit',title:'Edit sample',goal:'Update value',dependsOn:[],kind:'edit' as const,inputs:['sample.txt'],outputs:['sample.txt'],checkIds:['check']},{id:'verify',title:'Review result',goal:'Review current files',dependsOn:['edit'],kind:'verify' as const,inputs:['sample.txt'],outputs:['report'],checkIds:['check']}]};
class FixtureRunner implements Runner {
 count=0;pause?:{entered:()=>void;released:Promise<void>};
 async run(r:RunnerRequest,c:RunnerCallbacks,signal:AbortSignal){this.count++;if(r.purpose==='planning'){
  const denied=await c.onTool({toolCallId:id(),name:'write_file',args:{path:'not-allowed',content:'bad'}});assert.equal(denied.isError,true);
  const plan=structuredClone(draft);if(!r.checks.length)plan.nodes.forEach(n=>n.checkIds=[]);assert.equal((await c.onControl({kind:'update_plan',draft:plan,submit:true})).isError,undefined);
 }else {if(this.pause){this.pause.entered();await this.pause.released;}if(!signal.aborted){if(r.node?.id==='edit')await c.onTool({toolCallId:id(),name:'write_file',args:{path:'sample.txt',content:'updated\n'}});await c.onControl({kind:'complete',summary:'Finished with evidence'});}}
 return {summary:'fixture outcome',turns:1,usage:{input:5,output:3},aborted:signal.aborted};}
}
const executor:Executor={async execute(call,options,signal){if(signal.aborted)return {text:'aborted',isError:true};if(call.name==='write_file')writeFileSync(join(options.workdir,String(call.args.path)),String(call.args.content));if(call.name==='run_command'){assert.deepEqual(call.args.argv,['node','check.mjs']);return {text:readFileSync(join(options.workdir,'sample.txt'),'utf8')==='updated\n'?'pass':'fail',isError:readFileSync(join(options.workdir,'sample.txt'),'utf8')!=='updated\n'};}return {text:'ok'};}};
async function setup(t:test.TestContext,runner:Runner=new FixtureRunner()){
 const root=mkdtempSync(join(tmpdir(),'knotrail-core-')),source=join(root,'source'),dataDir=join(root,'data');mkdirSync(source);writeFileSync(join(source,'sample.txt'),'original\n');writeFileSync(join(source,'check.mjs'),'// immutable acceptance script\n');
 const env={...process.env,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_AUTHOR_NAME:'Fixture',GIT_AUTHOR_EMAIL:'fixture@example.org',GIT_COMMITTER_NAME:'Fixture',GIT_COMMITTER_EMAIL:'fixture@example.org'};
 for(const args of [['init'],['add','.'],['commit','-m','fixture']])execFileSync('git',args,{cwd:source,env,stdio:'ignore'});
 let secret:string|undefined;const app=createAppService({dataDir,secretStore:{get:()=>secret,set:v=>{secret=v;}},notify:()=>{},capabilities:{sandbox:true,platform:'darwin'},lockFd:-1,runner,executor});
 t.after(async()=>{await app.shutdown();rmSync(root,{recursive:true,force:true});});
 await app.command({type:'settings.save',patch:{model:{baseUrl:'http://127.0.0.1:12345/v1',modelId:'fixture'}}});const project=await app.command({type:'project.add',path:source}) as Project;
 return {app,source,dataDir,project,runner};
}
async function until(app:AppService,taskId:string,predicate:(s:TaskSnapshot)=>boolean):Promise<TaskSnapshot>{const deadline=Date.now()+5000;while(Date.now()<deadline){const s=await app.command({type:'task.snapshot',taskId}) as TaskSnapshot;if(predicate(s))return s;await new Promise(r=>setTimeout(r,10));}throw new Error('State did not settle: '+JSON.stringify(await app.command({type:'task.snapshot',taskId})));}
const create=(project:Project,overrides={})=>({type:'task.create',requestId:id(),projectId:project.id,objective:'Update sample',checks:[{id:'check',label:'Sample check',command:['node','check.mjs'],protectedPaths:['check.mjs']}],executionPolicy:'reviewBeforeExecute',mode:'once',...overrides});
test('validated plan rejects cycles, unknown dependencies and omitted user checks',()=>{assert.throws(()=>validatePlan({...draft,nodes:[{...draft.nodes[0],dependsOn:['edit']}]},[]),/cycle/);assert.throws(()=>validatePlan({...draft,nodes:[{...draft.nodes[0],dependsOn:['missing']}]},[]),/unknown/);assert.throws(()=>validatePlan({...draft,nodes:[{...draft.nodes[0],checkIds:[]}]},[{id:'check',label:'Required',command:['true'],protectedPaths:[]}]),/every/);});
test('create is durable/idempotent; ready gate precedes effects; final checks bind digest',async t=>{const {app,project,source}=await setup(t);const command=create(project);const created=await app.command(command) as TaskSnapshot;const duplicate=await app.command(command) as TaskSnapshot;assert.equal(created.task.id,duplicate.task.id);const ready=await until(app,created.task.id,s=>s.task.status==='ready');assert.equal(readFileSync(join(ready.task.workdir,'sample.txt'),'utf8'),'original\n');assert.equal(ready.actions.length,0);await app.command({type:'task.resume',taskId:created.task.id,expectedRevision:1});const done=await until(app,created.task.id,s=>s.task.status==='completed');assert.equal(done.nodes.filter(n=>n.status==='verified').length,2);assert.equal(done.checks.length,3);assert.ok(done.checks.every(c=>c.inputDigest===done.task.acceptedDigest));assert.equal(readFileSync(join(source,'sample.txt'),'utf8'),'original\n');assert.ok(done.artifacts.length===2&&done.artifacts[0]!.content.includes('updated'));assert.deepEqual(done.events.map(e=>e.seq),done.events.map((_,i)=>i+1));assert.ok(app.report(done.task.id).includes('## Event ledger'));});
test('no acceptance commands requires explicit user acceptance; stale decisions cannot complete',async t=>{const {app,project}=await setup(t);const created=await app.command(create(project,{checks:[],executionPolicy:'autoWithinGrant'})) as TaskSnapshot;const pending=await until(app,created.task.id,s=>s.task.status==='waiting_user');assert.equal(pending.decisions.length,1);const decision=pending.decisions[0]!;writeFileSync(join(pending.task.workdir,'sample.txt'),'external\n');await assert.rejects(app.command({type:'decision.answer',requestId:id(),taskId:created.task.id,decisionId:decision.id,answer:'accept',expectedRevision:1}),/changed/);});
test('goal change preserves immutable plans and rejects stale revision; retries invalidate downstream',async t=>{const {app,project}=await setup(t);const created=await app.command(create(project)) as TaskSnapshot;await until(app,created.task.id,s=>s.task.status==='ready');const preview=await app.command({type:'task.previewRetry',taskId:created.task.id,nodeId:'edit',expectedRevision:1}) as ImpactPreview;assert.deepEqual(preview.affected,['edit','verify']);assert.equal(preview.retained.length,0);const changed=await app.command({type:'task.previewRevision',taskId:created.task.id,objective:'Different goal',expectedRevision:1}) as ImpactPreview;await app.command({type:'task.applyImpact',requestId:id(),preview:changed});const ready=await until(app,created.task.id,s=>s.task.status==='ready');assert.equal(ready.task.revision,2);assert.equal(ready.plans.length,2);assert.equal(ready.plans[0]!.taskRevision,1);await assert.rejects(app.command({type:'task.applyImpact',requestId:id(),preview}),/changed/);});
test('crash recovery marks unfinished effects unknown and blocks automatic replay',async t=>{const {app,project}=await setup(t);const created=await app.command(create(project)) as TaskSnapshot;await until(app,created.task.id,s=>s.task.status==='ready');app.store.update(created.task.id,s=>{s.task.status='executing';s.runs.push({id:id(),taskId:s.task.id,taskRevision:1,purpose:'node',attempt:1,status:'running',startedAt:now(),inputDigest:'digest'});s.actions.push({id:id(),taskId:s.task.id,runId:s.runs.at(-1)!.id,toolCallId:id(),name:'write_file',argsDigest:'digest',status:'pending',startedAt:now()});});
 // A second service is a test-only reconstruction; desktop owner lock forbids two real owners.
 const reconstructed=createAppService({dataDir:(app as any).options.dataDir,secretStore:{get:()=>undefined,set:()=>{}},notify:()=>{},capabilities:{sandbox:true,platform:'darwin'},lockFd:-1,runner:new FixtureRunner(),executor});t.after(()=>reconstructed.shutdown());const recovered=await reconstructed.command({type:'task.snapshot',taskId:created.task.id}) as TaskSnapshot;assert.equal(recovered.task.status,'blocked');assert.equal(recovered.actions[0]!.status,'unknown');assert.equal(recovered.runs.at(-1)!.status,'unknown');});
test('IPC input rejects unknown fields and provider credentials in URLs; secrets never read back',async t=>{const {app}=await setup(t);await assert.rejects(app.command({type:'bootstrap',exec:'anything'}));await assert.rejects(app.command({type:'settings.save',patch:{model:{baseUrl:'https://name:secret@example.org'}}}));const key=id();const settings=await app.command({type:'settings.save',patch:{model:{apiKey:key}}});assert.ok(!JSON.stringify(settings).includes(key));assert.ok(!JSON.stringify(await app.command({type:'bootstrap'})).includes(key));});

test('the last permitted turn may complete the task without a phantom extra turn',async t=>{const {app,project}=await setup(t);const created=await app.command(create(project,{maxTurns:3,executionPolicy:'autoWithinGrant'})) as TaskSnapshot;const done=await until(app,created.task.id,s=>['completed','blocked'].includes(s.task.status));assert.equal(done.task.status,'completed');assert.equal(done.task.turnCount,3);});

test('cancellation makes pending decisions permanently unable to restart a task',async t=>{
 const runner:Runner={async run(r,c,signal){if(r.purpose==='planning'){const p=structuredClone(draft);p.nodes.forEach(n=>n.checkIds=[]);await c.onControl({kind:'update_plan',draft:p,submit:true});}else await c.onControl({kind:'decision',question:'Choose a format',options:['a','b']});return {summary:'decision',turns:1,usage:{input:0,output:0},aborted:signal.aborted};}};
 const {app,project}=await setup(t,runner);const created=await app.command(create(project,{checks:[],executionPolicy:'autoWithinGrant'})) as TaskSnapshot;const waiting=await until(app,created.task.id,s=>s.task.status==='waiting_user');const decision=waiting.decisions[0]!;
 await app.command({type:'task.cancel',taskId:created.task.id,expectedRevision:1});await assert.rejects(app.command({type:'decision.answer',requestId:id(),taskId:created.task.id,decisionId:decision.id,answer:'a',expectedRevision:1}),/not waiting/);
 const cancelled=await app.command({type:'task.snapshot',taskId:created.task.id}) as TaskSnapshot;assert.equal(cancelled.task.status,'cancelled');assert.equal(cancelled.runs.length,waiting.runs.length);assert.equal(cancelled.decisions[0]!.answer,'cancelled');app.store.update(created.task.id,s=>{s.task.expiresAt=new Date(Date.now()-1000).toISOString();});await assert.rejects(app.command({type:'decision.answer',requestId:id(),taskId:created.task.id,decisionId:decision.id,answer:'a',expectedRevision:1}),/not waiting/);assert.equal((await app.command({type:'task.snapshot',taskId:created.task.id}) as TaskSnapshot).task.status,'cancelled');
});
test('invalid merged settings do not replace a key, and endpoint changes clear old credentials',async t=>{
 const {app}=await setup(t);const key=id(),other=id();await app.command({type:'settings.save',patch:{model:{apiKey:key}}});const previous=(app as any).options.secretStore.get();
 await assert.rejects(app.command({type:'settings.save',patch:{model:{baseUrl:'https://provider.example.org/v1',apiKey:other,contextWindow:4096,maxTokens:8192}}}),/fit/);
 assert.equal((app as any).options.secretStore.get(),previous);
 const changed=await app.command({type:'settings.save',patch:{model:{baseUrl:'https://provider.example.org/v1'}}}) as any;assert.equal(changed.model.hasApiKey,false);assert.equal((app as any).options.secretStore.get(),'');
});
test('plan drafts may be incomplete, but only a complete plan can be committed',()=>{const partial={sequence:1,summary:'Reading the project',observations:[],nodes:[]};assert.equal(validatePlan(partial,[],false).nodes.length,0);assert.throws(()=>validatePlan(partial,[],true));});
test('issued impact previews cannot be forged or replayed with a new request ID',async t=>{
 const {app,project}=await setup(t);const created=await app.command(create(project)) as TaskSnapshot;await until(app,created.task.id,s=>s.task.status==='ready');const p=await app.command({type:'task.previewRetry',taskId:created.task.id,nodeId:'edit',expectedRevision:1}) as ImpactPreview;
 await assert.rejects(app.command({type:'task.applyImpact',requestId:id(),preview:{...p,affected:[]}}),/not issued/);
 const request={type:'task.applyImpact',requestId:id(),preview:p};await app.command(request);await app.command(request);await assert.rejects(app.command({...request,requestId:id()}),/not issued/);
});
test('Run deadline aborts an admitted parent tool and blocks automatic retry',async t=>{
 let cleaned=false,admitted=0;
 const runner:Runner={async run(r,c,signal){if(r.purpose==='planning'){const p=structuredClone(draft);p.nodes.forEach(n=>n.checkIds=[]);await c.onControl({kind:'update_plan',draft:p,submit:true});}else{await c.onTool({toolCallId:id(),name:'run_command',args:{argv:['never']}});if(!signal.aborted)await c.onControl({kind:'complete',summary:'unexpected'});}return {summary:'fixture',turns:1,usage:{input:0,output:0},aborted:signal.aborted};}};
 const {app,project}=await setup(t,runner);(app as any).executor={execute:async(_call:unknown,_options:unknown,signal:AbortSignal)=>{admitted++;await new Promise<void>(resolve=>signal.addEventListener('abort',()=>{cleaned=true;resolve();},{once:true}));return {text:'cancelled',isError:true};}};
 const created=await app.command(create(project,{checks:[],executionPolicy:'autoWithinGrant',maxRunMs:1000})) as TaskSnapshot;const blocked=await until(app,created.task.id,s=>s.task.status==='blocked');assert.ok(cleaned);assert.equal(admitted,1);assert.equal(blocked.nodes[0]!.status,'unknown');assert.match(blocked.task.error!,/timed out/);
});

test('an absolute task deadline cannot race the final node into completed',async t=>{
 const {app,project}=await setup(t);const created=await app.command(create(project,{mode:'finite',intervalMinutes:1,expiresAt:new Date(Date.now()+60000).toISOString()})) as TaskSnapshot;await until(app,created.task.id,s=>s.task.status==='ready');
 const slow:Runner={async run(_r,c,signal){await new Promise(resolve=>setTimeout(resolve,350));if(!signal.aborted)await c.onControl({kind:'complete',summary:'late'});return {summary:'late',turns:1,usage:{input:0,output:0},aborted:signal.aborted};}};(app as any).runner=slow;app.store.update(created.task.id,s=>{s.task.expiresAt=new Date(Date.now()+150).toISOString();});
 await app.command({type:'task.resume',taskId:created.task.id,expectedRevision:1});const expired=await until(app,created.task.id,s=>['expired','completed'].includes(s.task.status));assert.equal(expired.task.status,'expired');assert.equal(expired.task.acceptedDigest,undefined);
});
